version: '3.1' # version de docker compose
services: # servicios
  web: # servicio odoo
    image: odoo:17.0 # imagen de odoo
    restart: always # siempre reiniciar en caso de error
    depends_on: # dependencias
      - db
    ports: # puertos
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment: # variables de entorno
      - HOST=db # host de la base de datos
      - USER=odoo # usuario de la base de datos
      - PASSWORD=odoo # contraseña de la base de datos
  db: # servicio de base de datos
    image: postgres:15 # imagen de postgres
    ports: # puertos
      - "5432:5432"
    environment: # variables de entorno
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  pgadmin: # servicio de pgadmin
    image: dpage/pgadmin4 # imagen de pgadmin
    restart: always # siempre reiniciar en caso de error
    ports: # puertos
      - "8080:80"
    environment: # variables de entorno
      PGADMIN_DEFAULT_EMAIL: marcos@dam.com # email de pgadmin
      PGADMIN_DEFAULT_PASSWORD: 1234 # contraseña de pgadmin
    depends_on: # dependencias
      - db
volumes:
  odoo-web-data: